# Generated by Django 4.2.2 on 2023-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('community_id', models.IntegerField(blank=True, default=0, null=True)),
                ('post_type', models.IntegerField(blank=True, default=0, null=True)),
                ('member_type', models.CharField(blank=True, max_length=500, null=True)),
                ('allow_share', models.IntegerField(blank=True, default=0, null=True)),
                ('url_link', models.CharField(blank=True, max_length=500, null=True)),
                ('url_meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('url_meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('url_preview_image', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=500, null=True)),
                ('content_id', models.IntegerField(blank=True, default=0, null=True)),
                ('allow_comments', models.IntegerField(blank=True, default=1, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant_source', models.CharField(blank=True, max_length=500, null=True)),
                ('tenant_source_id', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_status', models.IntegerField(blank=True, default=0, null=True)),
                ('archive_status', models.IntegerField(blank=True, default=0, null=True)),
                ('visibility', models.IntegerField(blank=True, default=1, null=True)),
                ('delete_status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_tbl',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
