# Generated by Django 4.2.2 on 2023-06-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollList',
        ),
    ]
