# Generated by Django 4.2.2 on 2023-06-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_polllist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedList',
        ),
    ]
