# Generated by Django 4.2.2 on 2023-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedList',
        ),
    ]
