# Generated by Django 4.2.2 on 2023-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='Sentence',
        ),
        migrations.AddField(
            model_name='sentimentmodel',
            name='comment',
            field=models.CharField(default='some string', max_length=500),
        ),
    ]
