# Generated by Django 4.2.2 on 2023-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_sentimentmodel_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
