# Generated by Django 4.2.2 on 2023-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_sentimentmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentmodel',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=100),
        ),
    ]
