# Generated by Django 4.2.2 on 2023-07-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_sentimentmodel_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='sentiment',
        ),
    ]
